import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const readAbi = (artifact) =>
  JSON.parse(readFileSync(join(root, "contracts", "out", artifact), "utf8")).abi;
const claimFunctions = new Set([
  "artifactDigest", "campaignStandard", "claim", "claimBatch", "claimDeadline",
  "claimedCount", "claimDelegated", "claimStart", "destinationChainId",
  "destinationToken", "hashLeaf", "isClaimed", "merkleRoot", "migrationId", "nonces",
  "owner", "paused", "rootVersion", "snapshotBlock", "sourceBlockHash", "sourceChainId",
  "sourceContract",
]);
const tokenFunctions = new Set(["metadataFrozen", "minter", "minterLocked", "owner", "pendingOwner"]);
const claimErrors = new Set([
  "AlreadyClaimed", "ClaimWindowClosed", "EmptyBatch", "EnforcedPause", "ExpiredSignature",
  "InvalidAddress", "InvalidAmount", "InvalidNonce", "InvalidProof", "InvalidSignature",
  "MerkleProofInvalidMultiproof", "ReentrancyGuardReentrantCall", "UnauthorizedClaimAuthority",
  "ZeroRoot",
]);
const select = (abi, functions, errors = new Set()) =>
  abi.filter((item) =>
    (item.type === "function" && functions.has(item.name)) ||
    (item.type === "error" && errors.has(item.name))
  );
const source = `// Generated by scripts/generate-web-abi.mjs. Do not edit.\nexport const migrationClaimAbi = ${JSON.stringify(
  select(readAbi("ERC1155MigrationClaim.sol/ERC1155MigrationClaim.json"), claimFunctions, claimErrors),
  null,
  2,
)} as const;\n\nexport const migratedTokenAbi = ${JSON.stringify(
  select(readAbi("MigratedERC1155.sol/MigratedERC1155.json"), tokenFunctions),
  null,
  2,
)} as const;\n`;

writeFileSync(join(root, "apps", "web", "src", "abi.ts"), source);
